extends: airbnb-base
plugins:
  - import
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
globals:
  __: true
  describe: true
  it: true
  expect: true
  app: true
  beforeEach: true
  request: true
  td: true
  Joi: true
  joiAssert: true
